#!/usr/bin/bash
for node in {00..12}; do
    sbatch --ntasks=1 --job-name="cleanup-plai${node}" \
        --partition=plai \
        --time=1:00 --nodelist="plai${node}" \
        -o hpc_output/${EXP_NAME}_%j.out \
       plai_cleanup.sh
done
